### ISSUE TITLE
AttributeError: Can't get attribute 'SPPF'

### ISSUE THREAD

**Issue by xudh777** [cnyvfang/labelGo-Yolov5AutoLabelImg#12]
I successfully installed and configured the environment according to the instructions on GitHub, and then reported an error after running  
“AttributeError: Can't get attribute 'SPPF' on <module 'models.common'”， 
I refer to the link below to try to solve this problem
https://blog.csdn.net/cjy_colorful0806/article/details/120930204

But when encountering an error
“AttributeError: ‘Upsample‘ object has no attribute ‘recompute_scale_factor‘”
I refer to the link below to try to solve this problem
https://blog.csdn.net/qq_35207086/article/details/123879980

But when encountering an error
 “RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 28224”

I have tried several models such as: yolov5l.pt、yolov5l6.pt、yolov5s.pt、yolov5x6.pt. How can I run this project？？

**Comment by xudh777** [comment]
![微信截图_20220704155519](https://user-images.githubusercontent.com/52651891/177231234-7510c9aa-68e2-472d-a18a-788051925749.png)

**Comment by cnyvfang** [comment]
In fact, this project is based on YOLOv5 version 5 and therefore does not support version 6 of the model with SPPF. You can adapt the labelGo to version 6 by modifying the code yourself, or by replacing the models with version 5.

From: xudh1991 ***@***.***>
Date: Monday, July 4, 2022 at 15:36
To: cnyvfang/labelGo-Yolov5AutoLabelImg ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cnyvfang/labelGo-Yolov5AutoLabelImg] AttributeError: Can't get attribute 'SPPF' (Issue #12)

I successfully installed and configured the environment according to the instructions on GitHub, and then reported an error after running
“AttributeError: Can't get attribute 'SPPF' on <module 'models.common'”，
I refer to the link below to try to solve this problem
https://blog.csdn.net/cjy_colorful0806/article/details/120930204

But when encountering an error
“AttributeError: ‘Upsample‘ object has no attribute ‘recompute_scale_factor‘”
I refer to the link below to try to solve this problem
https://blog.csdn.net/qq_35207086/article/details/123879980

But when encountering an error
“RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 28224”

I have tried several models such as: yolov5l.pt、yolov5l6.pt、yolov5s.pt、yolov5x6.pt. How can I run this project？？
