### ISSUE TITLE
关于工具使用和个人的一些问题？

### ISSUE THREAD

**Issue by nowhereman1999** [cnyvfang/labelGo-Yolov5AutoLabelImg#2]
大佬你好，你是西南大学rm战队的成员吗？我是中北大学rm战队视觉组成员，现在负责用神经网络识别装甲板，目前已经用trt加速yolov5并部署到win下，后期会迁移到linux下，我感觉你这个工具挺好用的，就是我想问一下生成的标签格式就已经是yolo的吗，还是后期需要自己转？还有方便的话可以加个微信就数据集制作这块交流一下吗？

**Comment by cnyvfang** [comment]
你好你好，生成的就是yolo格式的，加我的QQ吧，47723516
