### ISSUE TITLE
labelGo autolabel doesn't work with  newest model output from YOLOv5

### ISSUE THREAD

**Issue by TECOLOGYxyz** [cnyvfang/labelGo-Yolov5AutoLabelImg#3]
Autoalabel doesn't work with models trained after YOLOv5 release 6 and gives the error below:
`AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from `

[https://github.com/ultralytics/yolov5/issues/5175](url)

**Comment by cnyvfang** [comment]
Yep, this version just can be used with YOLOv5 release 5.

I will update it when I have free time.
