### ISSUE TITLE
出现label还原问题

### ISSUE THREAD

**Issue by huaijinwoyu** [cnyvfang/labelGo-Yolov5AutoLabelImg#4]
问题背景：
                选择文件夹读取后（图片为多张60张），选择data model加载，加载完成后所有的图片都有默认设置的label。现在从第一张图片开始review，如果有的动物没框选上，手动增加标记框，并保存第一张照片。此时第二张照片会把之前加载好的label覆盖成其它，而不是之前加载好的。

**Comment by huaijinwoyu** [comment]
解决办法，在程序运行前，清空data下的predefined_classes.txt，只留自己的label。

**Comment by cnyvfang** [comment]
感谢您对问题的提交及解决
