### ISSUE TITLE
Can't get attribute 'SPPF'

### ISSUE THREAD

**Issue by chyphen7** [cnyvfang/labelGo-Yolov5AutoLabelImg#5]
Thanks for sharing your code.  I am trying to test run your code with yolov5s.pt and some data,  but getting the error message: Can't get attribute 'SPPF'".  Do you have any insight into what could be the source of the problem.  Also in Readm, there is a note stating "Please put classes.txt under the marked dataset folder in advance".  It is not clear to me what is marked dataset.   Should dataset be labeled first before running your code?  Please elaborate.  Or could you send me images and pt file, (along with class.txt) used in your demo (gif)?   Thanks in advance.

**Comment by cnyvfang** [comment]
The code in this repository only supports the v5 version of yolov5, spff is new for the v6 version and the code in this repository is not adapted for now.
